# Automower error codes: code -> (English, French).
# Source for the English texts: Husqvarna Automower Connect API error list (as used by aioautomower).
ERROR_CODES = {
    0: ("Unexpected error", "Erreur inattendue"),
    1: ("Outside working area", "Hors de la zone de travail"),
    2: ("No loop signal", "Pas de signal du câble périphérique"),
    3: ("Wrong loop signal", "Signal du câble périphérique incorrect"),
    4: ("Loop sensor problem, front", "Problème de capteur de câble, avant"),
    5: ("Loop sensor problem, rear", "Problème de capteur de câble, arrière"),
    6: ("Loop sensor problem, left", "Problème de capteur de câble, gauche"),
    7: ("Loop sensor problem, right", "Problème de capteur de câble, droite"),
    8: ("Wrong PIN code", "Code PIN incorrect"),
    9: ("Trapped", "Coincée"),
    10: ("Upside down", "Retournée"),
    11: ("Low battery", "Batterie faible"),
    12: ("Empty battery", "Batterie vide"),
    13: ("No drive", "Pas de propulsion"),
    14: ("Mower lifted", "Tondeuse soulevée"),
    15: ("Lifted", "Soulevée"),
    16: ("Stuck in charging station", "Bloquée dans la station de charge"),
    17: ("Charging station blocked", "Station de charge bloquée"),
    18: ("Collision sensor problem, rear", "Problème de capteur de collision, arrière"),
    19: ("Collision sensor problem, front", "Problème de capteur de collision, avant"),
    20: ("Wheel motor blocked, right", "Moteur de roue bloqué, droite"),
    21: ("Wheel motor blocked, left", "Moteur de roue bloqué, gauche"),
    22: ("Wheel drive problem, right", "Problème d'entraînement de roue, droite"),
    23: ("Wheel drive problem, left", "Problème d'entraînement de roue, gauche"),
    24: ("Cutting system blocked", "Système de coupe bloqué"),
    25: ("Cutting system blocked", "Système de coupe bloqué"),
    26: ("Invalid sub-device combination", "Combinaison de sous-ensembles non valide"),
    27: ("Settings restored", "Réglages restaurés"),
    28: ("Memory circuit problem", "Problème de circuit mémoire"),
    29: ("Slope too steep", "Pente trop raide"),
    30: ("Charging system problem", "Problème du système de charge"),
    31: ("STOP button problem", "Problème du bouton STOP"),
    32: ("Tilt sensor problem", "Problème du capteur d'inclinaison"),
    33: ("Mower tilted", "Tondeuse inclinée"),
    34: ("Cutting stopped - slope too steep", "Coupe arrêtée : pente trop raide"),
    35: ("Wheel motor overloaded, right", "Moteur de roue surchargé, droite"),
    36: ("Wheel motor overloaded, left", "Moteur de roue surchargé, gauche"),
    37: ("Charging current too high", "Courant de charge trop élevé"),
    38: ("Electronic problem", "Problème électronique"),
    39: ("Cutting motor problem", "Problème du moteur de coupe"),
    40: ("Limited cutting height range", "Plage de hauteur de coupe limitée"),
    41: ("Unexpected cutting height adjustment", "Réglage inattendu de la hauteur de coupe"),
    42: ("Limited cutting height range", "Plage de hauteur de coupe limitée"),
    43: ("Cutting height problem, drive", "Problème de hauteur de coupe, entraînement"),
    44: ("Cutting height problem, current", "Problème de hauteur de coupe, courant"),
    45: ("Cutting height problem, direction", "Problème de hauteur de coupe, direction"),
    46: ("Cutting height blocked", "Hauteur de coupe bloquée"),
    47: ("Cutting height problem", "Problème de hauteur de coupe"),
    48: ("No response from charger", "Pas de réponse du chargeur"),
    49: ("Ultrasonic problem", "Problème des capteurs à ultrasons"),
    50: ("Guide 1 not found", "Câble guide 1 introuvable"),
    51: ("Guide 2 not found", "Câble guide 2 introuvable"),
    52: ("Guide 3 not found", "Câble guide 3 introuvable"),
    53: ("GPS navigation problem", "Problème de navigation GPS"),
    54: ("Weak GPS signal", "Signal GPS faible"),
    55: ("Difficult finding home", "Difficulté à retrouver la station"),
    56: ("Guide calibration accomplished", "Calibrage du câble guide terminé"),
    57: ("Guide calibration failed", "Échec du calibrage du câble guide"),
    58: ("Temporary battery problem", "Problème temporaire de batterie"),
    59: ("Temporary battery problem", "Problème temporaire de batterie"),
    60: ("Temporary battery problem", "Problème temporaire de batterie"),
    61: ("Temporary battery problem", "Problème temporaire de batterie"),
    62: ("Battery restriction due to ambient temperature", "Batterie limitée à cause de la température ambiante"),
    63: ("Temporary battery problem", "Problème temporaire de batterie"),
    64: ("Temporary battery problem", "Problème temporaire de batterie"),
    65: ("Temporary battery problem", "Problème temporaire de batterie"),
    66: ("Battery problem", "Problème de batterie"),
    67: ("Battery problem", "Problème de batterie"),
    68: ("Temporary battery problem", "Problème temporaire de batterie"),
    69: ("Alarm! Mower switched off", "Alarme ! Tondeuse éteinte"),
    70: ("Alarm! Mower stopped", "Alarme ! Tondeuse arrêtée"),
    71: ("Alarm! Mower lifted", "Alarme ! Tondeuse soulevée"),
    72: ("Alarm! Mower tilted", "Alarme ! Tondeuse inclinée"),
    73: ("Alarm! Mower in motion", "Alarme ! Tondeuse déplacée"),
    74: ("Alarm! Outside geofence", "Alarme ! Hors de la zone de géorepérage"),
    75: ("Connection changed", "Connexion modifiée"),
    76: ("Connection NOT changed", "Connexion NON modifiée"),
    77: ("Com board not available", "Carte de communication indisponible"),
    78: ("Slipped - situation not solved with moving pattern", "Patinage : situation non résolue par les manœuvres"),
    79: ("Invalid battery combination", "Combinaison de batteries non valide"),
    80: ("Cutting system imbalance", "Déséquilibre du système de coupe"),
    81: ("Safety function faulty", "Fonction de sécurité défaillante"),
    82: ("Wheel motor blocked, rear right", "Moteur de roue bloqué, arrière droite"),
    83: ("Wheel motor blocked, rear left", "Moteur de roue bloqué, arrière gauche"),
    84: ("Wheel drive problem, rear right", "Problème d'entraînement de roue, arrière droite"),
    85: ("Wheel drive problem, rear left", "Problème d'entraînement de roue, arrière gauche"),
    86: ("Wheel motor overloaded, rear right", "Moteur de roue surchargé, arrière droite"),
    87: ("Wheel motor overloaded, rear left", "Moteur de roue surchargé, arrière gauche"),
    88: ("Angular sensor problem", "Problème du capteur angulaire"),
    89: ("Invalid system configuration", "Configuration système non valide"),
    90: ("No power in charging station", "Pas d'alimentation dans la station de charge"),
    91: ("Switch cord problem", "Problème de cordon de commutation"),
    92: ("Work area not valid", "Zone de travail non valide"),
    93: ("No accurate position from satellites", "Pas de position satellite précise"),
    94: ("Reference station communication problem", "Problème de communication avec la station de référence"),
    95: ("Folding sensor activated", "Capteur de pliage activé"),
    96: ("Right brush motor overloaded", "Moteur de brosse droite surchargé"),
    97: ("Left brush motor overloaded", "Moteur de brosse gauche surchargé"),
    98: ("Ultrasonic sensor 1 defect", "Capteur à ultrasons 1 défectueux"),
    99: ("Ultrasonic sensor 2 defect", "Capteur à ultrasons 2 défectueux"),
    100: ("Ultrasonic sensor 3 defect", "Capteur à ultrasons 3 défectueux"),
    101: ("Ultrasonic sensor 4 defect", "Capteur à ultrasons 4 défectueux"),
    102: ("Cutting drive motor 1 defect", "Moteur de coupe 1 défectueux"),
    103: ("Cutting drive motor 2 defect", "Moteur de coupe 2 défectueux"),
    104: ("Cutting drive motor 3 defect", "Moteur de coupe 3 défectueux"),
    105: ("Lift sensor defect", "Capteur de soulèvement défectueux"),
    106: ("Collision sensor defect", "Capteur de collision défectueux"),
    107: ("Docking sensor defect", "Capteur d'amarrage défectueux"),
    108: ("Folding cutting deck sensor defect", "Capteur du plateau de coupe pliable défectueux"),
    109: ("Loop sensor defect", "Capteur de câble défectueux"),
    110: ("Collision sensor error", "Erreur du capteur de collision"),
    111: ("No confirmed position", "Position non confirmée"),
    112: ("Cutting system major imbalance", "Déséquilibre important du système de coupe"),
    113: ("Complex working area", "Zone de travail complexe"),
    114: ("Too high discharge current", "Courant de décharge trop élevé"),
    115: ("Too high internal current", "Courant interne trop élevé"),
    116: ("High charging power loss", "Perte de puissance de charge élevée"),
    117: ("High internal power loss", "Perte de puissance interne élevée"),
    118: ("Charging system problem", "Problème du système de charge"),
    119: ("Zone generator problem", "Problème du générateur de zone"),
    120: ("Internal voltage error", "Erreur de tension interne"),
    121: ("High internal temperature", "Température interne élevée"),
    122: ("CAN error", "Erreur CAN"),
    123: ("Destination not reachable", "Destination inaccessible"),
    124: ("Destination blocked", "Destination bloquée"),
    125: ("Battery needs replacement", "La batterie doit être remplacée"),
    126: ("Battery near end of life", "Batterie en fin de vie"),
    127: ("Battery problem", "Problème de batterie"),
    128: ("Multiple reference stations detected", "Plusieurs stations de référence détectées"),
    129: ("Auxiliary cutting means blocked", "Dispositif de coupe auxiliaire bloqué"),
    130: ("Imbalanced auxiliary cutting disc detected", "Disque de coupe auxiliaire déséquilibré"),
    131: ("Lifted in link arm", "Soulevée au niveau du bras de liaison"),
    132: ("EPOS accessory missing", "Accessoire EPOS manquant"),
    133: ("Bluetooth communication with charging station failed", "Échec de la communication Bluetooth avec la station de charge"),
    134: ("Invalid software configuration", "Configuration logicielle non valide"),
    135: ("Radar problem", "Problème du radar"),
    136: ("Work area tampered", "Zone de travail modifiée"),
    137: ("High temperature in cutting motor, right", "Température élevée du moteur de coupe, droite"),
    138: ("High temperature in cutting motor, center", "Température élevée du moteur de coupe, centre"),
    139: ("High temperature in cutting motor, left", "Température élevée du moteur de coupe, gauche"),
    141: ("Wheel brush motor problem", "Problème du moteur de brosse de roue"),
    142: ("Self diagnostic error", "Erreur d'autodiagnostic"),
    143: ("Accessory power problem", "Problème d'alimentation d'un accessoire"),
    144: ("Boundary wire problem", "Problème de câble périphérique"),
    145: ("No correction data available", "Aucune donnée de correction disponible"),
    147: ("Cutting disc lost", "Disque de coupe perdu"),
    148: ("Chassis collision", "Collision du châssis"),
    149: ("Vision system malfunction", "Dysfonctionnement du système de vision"),
    151: ("Poor vision performance", "Performances de vision insuffisantes"),
    152: ("Vision system error", "Erreur du système de vision"),
    153: ("Charging aborted", "Charge interrompue"),
    154: ("Water hose found in working area", "Tuyau d'arrosage détecté dans la zone de travail"),
    155: ("PIN code changed", "Code PIN modifié"),
    156: ("Wi-Fi settings changed", "Réglages Wi-Fi modifiés"),
    157: ("Bluetooth settings changed", "Réglages Bluetooth modifiés"),
    158: ("Cellular settings changed", "Réglages cellulaires modifiés"),
    159: ("Mower installation position changed", "Position d'installation de la tondeuse modifiée"),
    160: ("Firmware has been updated", "Le micrologiciel a été mis à jour"),
    161: ("No charging station signal", "Pas de signal de la station de charge"),
    701: ("Connectivity problem", "Problème de connectivité"),
    702: ("Connectivity settings restored", "Réglages de connectivité restaurés"),
    703: ("Connectivity problem", "Problème de connectivité"),
    704: ("Connectivity problem", "Problème de connectivité"),
    705: ("Connectivity problem", "Problème de connectivité"),
    706: ("Poor signal quality", "Mauvaise qualité du signal"),
    707: ("SIM card requires PIN", "La carte SIM demande un code PIN"),
    708: ("SIM card locked", "Carte SIM verrouillée"),
    709: ("SIM card not found", "Carte SIM introuvable"),
    710: ("SIM card locked", "Carte SIM verrouillée"),
    711: ("SIM card locked", "Carte SIM verrouillée"),
    712: ("SIM card locked", "Carte SIM verrouillée"),
    713: ("Geofence problem", "Problème de géorepérage"),
    714: ("Geofence problem", "Problème de géorepérage"),
    715: ("Connectivity problem", "Problème de connectivité"),
    716: ("Connectivity problem", "Problème de connectivité"),
    717: ("SMS could not be sent", "Impossible d'envoyer le SMS"),
    724: ("Communication circuit board software must be updated", "Le logiciel de la carte de communication doit être mis à jour"),
}
