"""Generates the .resw resource files of HusqaCockpit.App from ui_strings.py and error_codes.py.

Usage (from the repository root):  python tools/strings/generate_resw.py
Edit the Python tables, never the generated .resw files.
"""
from pathlib import Path
from xml.sax.saxutils import escape

from error_codes import ERROR_CODES
from ui_strings import STRINGS

ROOT = Path(__file__).resolve().parents[2]
STRINGS_DIR = ROOT / "src" / "HusqaCockpit.App" / "Strings"
LANGUAGES = {"en-US": 0, "fr-FR": 1}

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/strings/generate_resw.py. Do not edit by hand. -->
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""


def write(path: Path, entries: dict[str, str]) -> None:
    lines = [HEADER]
    for key, value in entries.items():
        lines.append(f'  <data name="{escape(key, {chr(34): "&quot;"})}" xml:space="preserve"><value>{escape(value)}</value></data>\n')
    lines.append("</root>\n")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    for language, index in LANGUAGES.items():
        write(STRINGS_DIR / language / "Resources.resw", {k: v[index] for k, v in STRINGS.items()})
        write(STRINGS_DIR / language / "ErrorCodes.resw", {f"E{code}": texts[index] for code, texts in ERROR_CODES.items()})
    print(f"{len(STRINGS)} UI strings and {len(ERROR_CODES)} error codes written for {', '.join(LANGUAGES)}")


if __name__ == "__main__":
    main()
