# UI strings: key -> (English, French).
# Keys containing a dot are used by x:Uid in XAML; the others are read from code (Loc.Get/Format).
TT = "[using:Microsoft.UI.Xaml.Controls]ToolTipService.ToolTip"
AN = "[using:Microsoft.UI.Xaml.Automation]AutomationProperties.Name"

STRINGS = {
    "AppName": ("HusqA Cockpit", "HusqA Cockpit"),
    "ErrorCode_Unknown": ("Unknown error (code {0})", "Erreur inconnue (code {0})"),
    "Error_NotConnected": ("Not connected to Husqvarna. Check the API key in the settings.", "Non connecté à Husqvarna. Vérifiez la clé d'API dans les paramètres."),

    # ----- Status sentences -----
    "Status_Disconnected": ("Disconnected", "Déconnectée"),
    "Status_LastSeen": ("Last contact {0}", "Dernier contact {0}"),
    "Status_ErrorSince": ("Since {0}", "Depuis {0}"),
    "Status_Stopped": ("Stopped", "Arrêtée"),
    "Status_StoppedDetail": ("Manual action required on the mower", "Une intervention sur la tondeuse est nécessaire"),
    "Status_Paused": ("Paused", "En pause"),
    "Status_PausedDetail": ("Waiting in the garden", "Attend dans le jardin"),
    "Status_NextStart": ("Next start {0}", "Prochain départ {0}"),
    "Status_Mowing": ("Mowing", "Tond"),
    "Status_MowingOverride": ("Manual start (outside the schedule)", "Démarrage manuel (hors planning)"),
    "Status_MowingSchedule": ("Following the schedule", "Selon le planning"),
    "Status_Charging": ("Charging", "En charge"),
    "Status_ChargingRemaining": ("{0} left", "Encore {0}"),
    "Status_Parked": ("Parked", "Garée"),
    "Status_ParkedUntil": ("Until {0}", "Jusqu'à {0}"),
    "Status_ParkedUntilFurtherNotice": ("Parked until further notice", "Garée jusqu'à nouvel ordre"),
    "Status_ParkedUntilFurtherNoticeDetail": ("Use “Resume” to follow the schedule again", "Utilisez « Reprendre » pour revenir au planning"),
    "Status_NoSchedule": ("No upcoming start", "Aucun départ prévu"),

    "When_Today": ("today at {0}", "aujourd'hui à {0}"),
    "When_Tomorrow": ("tomorrow at {0}", "demain à {0}"),
    "When_Yesterday": ("yesterday at {0}", "hier à {0}"),
    "When_Date": ("{0} at {1}", "{0} à {1}"),
    "When_DatePattern": ("ddd, MMM d", "ddd d MMM"),
    "Relative_JustNow": ("just now", "à l'instant"),
    "Relative_Minutes": ("{0} min ago", "il y a {0} min"),
    "Relative_Hours": ("{0} h ago", "il y a {0} h"),
    "Relative_Days": ("{0} d ago", "il y a {0} j"),
    "Duration_Minutes": ("{0} min", "{0} min"),
    "Duration_HoursMinutes": ("{0} h {1:00}", "{0} h {1:00}"),
    "Schedule_EveryDay": ("Every day", "Tous les jours"),
    "Unit_Hours": ("{0} h", "{0} h"),
    "Unit_Kilometers": ("{0} km", "{0} km"),

    # ----- Enum values -----
    "MowerActivity_Unknown": ("Unknown", "Inconnue"),
    "MowerActivity_NotApplicable": ("Not applicable", "Non applicable"),
    "MowerActivity_Mowing": ("Mowing", "Tond"),
    "MowerActivity_GoingHome": ("Going back to the station", "Retourne à la station"),
    "MowerActivity_Charging": ("Charging", "En charge"),
    "MowerActivity_Leaving": ("Leaving the station", "Quitte la station"),
    "MowerActivity_ParkedInCs": ("Parked in the station", "Garée dans la station"),
    "MowerActivity_StoppedInGarden": ("Stopped in the garden", "Arrêtée dans le jardin"),
    "MowerState_Unknown": ("Unknown", "Inconnu"),
    "MowerState_NotApplicable": ("Not applicable", "Non applicable"),
    "MowerState_Paused": ("Paused", "En pause"),
    "MowerState_InOperation": ("In operation", "En fonctionnement"),
    "MowerState_WaitUpdating": ("Software update in progress", "Mise à jour logicielle en cours"),
    "MowerState_WaitPowerUp": ("Starting up", "Démarrage en cours"),
    "MowerState_Restricted": ("Restricted (schedule or override)", "Restreinte (planning ou commande)"),
    "MowerState_Off": ("Switched off", "Éteinte"),
    "MowerState_Stopped": ("Stopped", "Arrêtée"),
    "MowerState_Error": ("Error", "Erreur"),
    "MowerState_FatalError": ("Fatal error", "Erreur grave"),
    "MowerState_ErrorAtPowerUp": ("Error at start-up", "Erreur au démarrage"),
    "MowerMode_Unknown": ("Unknown", "Inconnu"),
    "MowerMode_MainArea": ("Main area", "Zone principale"),
    "MowerMode_SecondaryArea": ("Secondary area", "Zone secondaire"),
    "MowerMode_Home": ("Home (parked)", "Home (garée)"),
    "MowerMode_Demo": ("Demo", "Démo"),
    "MowerMode_Poi": ("Point of interest", "Point d'intérêt"),
    "InactiveReason_Unknown": ("Unknown", "Inconnue"),
    "InactiveReason_None": ("None", "Aucune"),
    "InactiveReason_Planning": ("Planning its route", "Planifie son trajet"),
    "InactiveReason_SearchingForSatellites": ("Searching for satellites", "Recherche de satellites"),
    "RestrictedReason_Unknown": ("Unknown restriction", "Restriction inconnue"),
    "RestrictedReason_None": ("No restriction", "Aucune restriction"),
    "RestrictedReason_WeekSchedule": ("Weekly schedule", "Planning hebdomadaire"),
    "RestrictedReason_ParkOverride": ("Parked manually", "Garée manuellement"),
    "RestrictedReason_Sensor": ("Restricted by a sensor", "Restriction par un capteur"),
    "RestrictedReason_DailyLimit": ("Daily limit reached", "Limite quotidienne atteinte"),
    "RestrictedReason_Fota": ("Software update", "Mise à jour logicielle"),
    "RestrictedReason_Frost": ("Frost protection", "Protection contre le gel"),
    "RestrictedReason_AllWorkAreasCompleted": ("All work areas completed", "Toutes les zones sont terminées"),
    "RestrictedReason_External": ("External restriction (smart home, voice assistant…)", "Restriction externe (domotique, assistant vocal…)"),
    "RestrictedReason_NotApplicable": ("Not applicable", "Non applicable"),
    "HeadlightMode_Unknown": ("—", "—"),
    "HeadlightMode_AlwaysOn": ("Always on", "Toujours allumés"),
    "HeadlightMode_AlwaysOff": ("Always off", "Toujours éteints"),
    "HeadlightMode_EveningOnly": ("Evening only", "Le soir uniquement"),
    "HeadlightMode_EveningAndNight": ("Evening and night", "Soir et nuit"),
    "TaskNotificationMode_None": ("None", "Aucune"),
    "TaskNotificationMode_EndOnly": ("Mowing end only", "Fin de tonte seulement"),
    "TaskNotificationMode_StartAndEnd": ("Mowing start and end", "Début et fin de tonte"),
    "MessageSeverity_Unknown": ("Unknown", "Inconnue"),
    "MessageSeverity_Fatal": ("Fatal", "Critique"),
    "MessageSeverity_Error": ("Error", "Erreur"),
    "MessageSeverity_Warning": ("Warning", "Avertissement"),
    "MessageSeverity_Info": ("Information", "Information"),
    "MessageSeverity_Debug": ("Debug", "Débogage"),
    "MessageSeverity_Sw": ("Software", "Logiciel"),

    # ----- Mower card / detail -----
    "Mower_ErrorCode": ("Error {0}: {1}", "Erreur {0} : {1}"),
    "Mower_Updated": ("Updated {0}", "Mis à jour {0}"),
    "Mower_NoPosition": ("No position available", "Aucune position disponible"),
    "Stats_CuttingTime": ("Total cutting time", "Temps de coupe total"),
    "Stats_RunningTime": ("Total running time", "Temps de fonctionnement total"),
    "Stats_ChargingTime": ("Total charging time", "Temps de charge total"),
    "Stats_SearchingTime": ("Time spent searching for the station", "Temps de recherche de la station"),
    "Stats_ChargingCycles": ("Charging cycles", "Cycles de charge"),
    "Stats_Collisions": ("Collisions", "Collisions"),
    "Stats_Distance": ("Distance driven", "Distance parcourue"),
    "Stats_BladeUsage": ("Blade usage since last reset", "Utilisation des lames depuis la remise à zéro"),

    "Command_Failed": ("Command failed: {0}", "Échec de la commande : {0}"),
    "Command_FailedFor": ("The command failed for: {0}", "La commande a échoué pour : {0}"),
    "Command_StartSent": ("Start command sent.", "Ordre de démarrage envoyé."),
    "Command_PauseSent": ("Pause command sent.", "Ordre de pause envoyé."),
    "Command_ResumeSent": ("The mower will follow its schedule again.", "La tondeuse va reprendre son planning."),
    "Command_ParkSent": ("Park command sent.", "Ordre de retour à la station envoyé."),
    "Command_ConfirmSent": ("Error acknowledged.", "Erreur acquittée."),
    "Command_SettingsSent": ("Setting sent to the mower.", "Réglage envoyé à la tondeuse."),
    "Command_BladeResetSent": ("Blade usage counter reset.", "Compteur d'utilisation des lames remis à zéro."),
    "Command_ParkAllSent": ("All mowers are going back to their station until further notice.", "Toutes les tondeuses retournent à leur station jusqu'à nouvel ordre."),
    "Command_ResumeAllSent": ("All mowers will follow their schedule again.", "Toutes les tondeuses reprennent leur planning."),

    # ----- Tray -----
    "Tray_Summary": ("{0} mower(s) · {1} mowing", "{0} tondeuse(s) · {1} en tonte"),
    "Tray_Errors": ("{0} with a problem", "{0} en erreur"),
    "Tray_Open": ("Open HusqA Cockpit", "Ouvrir HusqA Cockpit"),
    "Tray_Refresh": ("Refresh", "Actualiser"),
    "Tray_ParkAll": ("Park all mowers", "Garer toutes les tondeuses"),
    "Tray_ResumeAll": ("Resume all schedules", "Reprendre tous les plannings"),
    "Tray_Quit": ("Quit", "Quitter"),

    # ----- Connection status -----
    "Connection_Live": ("Real time", "Temps réel"),
    "Connection_Polling": ("Periodic refresh", "Actualisation périodique"),
    "Connection_Starting": ("Connecting…", "Connexion…"),
    "Connection_Offline": ("Offline", "Hors ligne"),
    "Connection_NotConfigured": ("API key required", "Clé d'API requise"),
    "Banner_NoCredentialsTitle": ("Welcome!", "Bienvenue !"),
    "Banner_NoCredentials": ("Enter your Husqvarna API key to see your mowers.", "Saisissez votre clé d'API Husqvarna pour afficher vos tondeuses."),
    "Banner_StartingTitle": ("Connecting to Husqvarna…", "Connexion à Husqvarna…"),
    "Banner_PollingTitle": ("Real-time updates unavailable", "Mises à jour en temps réel indisponibles"),
    "Banner_Polling": ("The mowers are refreshed periodically.", "Les tondeuses sont actualisées périodiquement."),
    "Banner_Forbidden": ("Husqvarna refused the real-time connection: on the developer portal, check that your application is connected to the “Automower Connect API” (renewing the key often helps). Meanwhile the mowers are refreshed periodically.",
                         "Husqvarna a refusé la connexion temps réel : sur le portail développeur, vérifiez que votre application est connectée à « Automower Connect API » (renouveler la clé aide souvent). En attendant, les tondeuses sont actualisées périodiquement."),
    "Banner_PollingTimes": ("Last update {0}, next {1}.", "Dernière mise à jour {0}, prochaine {1}."),
    "Banner_AuthFailedTitle": ("API key rejected", "Clé d'API refusée"),
    "Banner_AuthFailed": ("Husqvarna rejected the application key or secret. Check them in the settings.", "Husqvarna a refusé la clé ou le secret de l'application. Vérifiez-les dans les paramètres."),
    "Banner_OfflineTitle": ("Husqvarna servers unreachable", "Serveurs Husqvarna injoignables"),
    "Banner_RetryAt": ("Next attempt at {0}.", "Nouvel essai à {0}."),

    # ----- Settings (code) -----
    "Settings_TestSuccess": ("Connection successful: {0} mower(s) found.", "Connexion réussie : {0} tondeuse(s) trouvée(s)."),
    "Settings_TestTooManyLogins": ("Husqvarna refuses logins that are too close together. Wait a minute and try again.", "Husqvarna refuse les connexions trop rapprochées. Patientez une minute puis réessayez."),
    "Settings_TestInvalid": ("The application key or secret is incorrect.", "La clé ou le secret de l'application est incorrect."),
    "Settings_TestForbidden": ("The key is valid but cannot access the Automower Connect API. Connect this API to your application on the developer portal.", "La clé est valide mais n'a pas accès à l'API Automower Connect. Connectez cette API à votre application sur le portail développeur."),
    "Settings_TestError": ("Test failed: {0}", "Échec du test : {0}"),
    "Settings_Saved": ("Key saved. Connecting…", "Clé enregistrée. Connexion en cours…"),
    "Settings_Deleted": ("Key deleted from this computer.", "Clé supprimée de cet ordinateur."),
    "Settings_EveryMinutes": ("Every {0} minutes", "Toutes les {0} minutes"),
    "Settings_Quota": ("API requests sent this month from this computer: {0} (the API is limited to {1} requests per month).", "Requêtes envoyées à l'API ce mois-ci depuis cet ordinateur : {0} (l'API est limitée à {1} requêtes par mois)."),
    "Settings_Version": ("HusqA Cockpit {0}", "HusqA Cockpit {0}"),

    # ----- Notifications -----
    "Notification_ErrorTitle": ("{0} has a problem", "{0} a un problème"),
    "Notification_AlarmTitle": ("⚠ Alarm on {0}", "⚠ Alarme sur {0}"),
    "Notification_ClearedTitle": ("{0} is working again", "{0} fonctionne à nouveau"),
    "Notification_ClearedBody": ("Resolved: {0}", "Résolu : {0}"),
    "Notification_StoppedTitle": ("{0} has stopped", "{0} s'est arrêtée"),
    "Notification_StoppedBody": ("A manual action on the mower is required.", "Une intervention sur la tondeuse est nécessaire."),
    "Notification_DisconnectedTitle": ("{0} is disconnected", "{0} est déconnectée"),
    "Notification_DisconnectedBody": ("The mower no longer communicates with the Husqvarna cloud.", "La tondeuse ne communique plus avec le cloud Husqvarna."),
    "Notification_ReconnectedTitle": ("{0} is connected again", "{0} est de nouveau connectée"),
    "Notification_ReconnectedBody": ("Communication with the mower is restored.", "La communication avec la tondeuse est rétablie."),
    "Notification_TaskStartedTitle": ("{0} starts mowing", "{0} commence à tondre"),
    "Notification_TaskStartedSchedule": ("Following its schedule.", "Selon son planning."),
    "Notification_TaskStartedApplication": ("Started from HusqA Cockpit.", "Lancée depuis HusqA Cockpit."),
    "Notification_TaskStartedManual": ("Started manually, outside its schedule.", "Démarrage manuel, hors planning."),
    "Notification_TaskStartedUnknown": ("Mowing has started.", "La tonte a démarré."),
    "Notification_TaskFinishedTitle": ("{0} has finished mowing", "{0} a terminé sa tonte"),
    "Notification_TaskFinishedDuration": ("Duration: {0}, recharges included.", "Durée : {0}, recharges comprises."),
    "Notification_TaskFinishedUnknown": ("Mowing is over.", "La tonte est terminée."),
    "Notification_Open": ("Open", "Ouvrir"),
    "Notification_TestTitle": ("Test notification", "Notification de test"),
    "Notification_TestBody": ("This is how HusqA Cockpit will warn you when a mower needs attention.", "Voici comment HusqA Cockpit vous préviendra quand une tondeuse a besoin d'attention."),
    "Notification_TrayHintTitle": ("HusqA Cockpit is still running", "HusqA Cockpit reste actif"),
    "Notification_TrayHintBody": ("It keeps watching your mowers from the notification area. Right-click its icon to quit.", "Il continue de surveiller vos tondeuses depuis la zone de notification. Clic droit sur son icône pour quitter."),

    "Dialog_ResetBladesTitle": ("Reset the blade counter?", "Remettre à zéro le compteur des lames ?"),
    "Dialog_ResetBladesText": ("Do this after replacing the blades of {0}.", "À faire après avoir remplacé les lames de {0}."),
    "Dialog_Reset": ("Reset", "Remettre à zéro"),
    "Dialog_Cancel": ("Cancel", "Annuler"),

    # ===== x:Uid =====
    "Nav_Dashboard.Content": ("My mowers", "Mes tondeuses"),

    "Dashboard_Title.Text": ("My mowers", "Mes tondeuses"),
    "Dashboard_ResumeAll.Label": ("Resume all", "Tout reprendre"),
    f"Dashboard_ResumeAll.{TT}": ("All mowers follow their schedule again", "Toutes les tondeuses reprennent leur planning"),
    "Dashboard_ParkAll.Label": ("Park all", "Tout garer"),
    f"Dashboard_ParkAll.{TT}": ("Send all mowers back to their station until further notice", "Renvoyer toutes les tondeuses à leur station jusqu'à nouvel ordre"),
    "Dashboard_Refresh.Label": ("Refresh", "Actualiser"),
    "Dashboard_EmptyTitle.Text": ("No mowers yet", "Aucune tondeuse pour l'instant"),
    "Dashboard_EmptyText.Text": ("Your mowers will appear here as soon as the connection to Husqvarna is established.", "Vos tondeuses apparaîtront ici dès que la connexion à Husqvarna sera établie."),
    "Banner_OpenSettings.Content": ("Open settings", "Ouvrir les paramètres"),

    f"Card_Details.{TT}": ("Details", "Détails"),
    f"Card_Details.{AN}": ("Details", "Détails"),
    f"Card_CuttingHeight.{TT}": ("Cutting height", "Hauteur de coupe"),
    f"Card_Headlights.{TT}": ("Headlights", "Phares"),

    "Action_Start.Text": ("Mow", "Tondre"),
    f"Action_StartButton.{TT}": ("Mow now, outside the schedule", "Tondre maintenant, hors planning"),
    f"Action_StartButton.{AN}": ("Mow", "Tondre"),
    "Action_StartLong.Text": ("Mow now", "Tondre maintenant"),
    "Action_Start30.Text": ("For 30 minutes", "Pendant 30 minutes"),
    "Action_Start60.Text": ("For 1 hour", "Pendant 1 heure"),
    "Action_Start120.Text": ("For 2 hours", "Pendant 2 heures"),
    "Action_Start180.Text": ("For 3 hours", "Pendant 3 heures"),
    "Action_Start360.Text": ("For 6 hours", "Pendant 6 heures"),
    "Action_Pause.Text": ("Pause", "Pause"),
    f"Action_PauseButton.{TT}": ("Stop where it is", "S'arrêter sur place"),
    f"Action_PauseButton.{AN}": ("Pause", "Pause"),
    "Action_Park.Text": ("Park", "Garer"),
    f"Action_ParkButton.{TT}": ("Go back to the charging station", "Retourner à la station de charge"),
    f"Action_ParkButton.{AN}": ("Park", "Garer"),
    "Action_ParkLong.Text": ("Back to station", "Retour à la station"),
    "Action_ParkNextSchedule.Text": ("Until the next scheduled start", "Jusqu'au prochain créneau"),
    "Action_ParkFurtherNotice.Text": ("Until further notice", "Jusqu'à nouvel ordre"),
    "Action_Park180.Text": ("For 3 hours", "Pendant 3 heures"),
    "Action_Park360.Text": ("For 6 hours", "Pendant 6 heures"),
    "Action_Park1440.Text": ("For 24 hours", "Pendant 24 heures"),
    "Action_Resume.Text": ("Resume", "Reprendre"),
    f"Action_ResumeButton.{TT}": ("Follow the weekly schedule again", "Revenir au planning hebdomadaire"),
    f"Action_ResumeButton.{AN}": ("Resume schedule", "Reprendre le planning"),
    "Action_ResumeLong.Text": ("Resume schedule", "Reprendre le planning"),

    "Detail_Serial.Text": ("Serial no. ", "N° de série "),
    "Detail_ConfirmError.Content": ("Acknowledge", "Acquitter"),
    "Detail_Activity.Text": ("Activity", "Activité"),
    "Detail_State.Text": ("State", "État"),
    "Detail_Mode.Text": ("Mode", "Mode"),
    "Detail_LastUpdate.Text": ("Last update", "Dernière mise à jour"),
    "Detail_CommandsHeader.Text": ("Commands", "Commandes"),
    "Detail_SettingsHeader.Text": ("Settings", "Réglages"),
    "Detail_CuttingHeight.Text": ("Cutting height (1–9)", "Hauteur de coupe (1–9)"),
    "Detail_Headlights.Text": ("Headlights", "Phares"),
    "Detail_Apply.Content": ("Apply", "Appliquer"),
    f"Detail_CuttingHeightSlider.{AN}": ("Cutting height", "Hauteur de coupe"),
    f"Detail_HeadlightsCombo.{AN}": ("Headlights", "Phares"),
    "Detail_ScheduleHeader.Text": ("Weekly schedule", "Planning hebdomadaire"),
    "Detail_NoSchedule.Text": ("No schedule defined.", "Aucun planning défini."),
    "Detail_EditSchedule.Content": ("Edit schedule", "Modifier le planning"),
    "Detail_ScheduleWorkAreas.Text": ("This mower uses work areas: its schedule cannot be edited here yet.", "Cette tondeuse utilise des zones de travail : son planning n'est pas encore modifiable ici."),
    "ScheduleEditorDialog.Title": ("Weekly schedule", "Planning hebdomadaire"),
    "ScheduleEditorDialog.PrimaryButtonText": ("Send to the mower", "Envoyer à la tondeuse"),
    "ScheduleEditorDialog.CloseButtonText": ("Cancel", "Annuler"),
    "ScheduleEditor_Hint.Text": ("The mower mows during these time slots, on the selected days. A slot can end at midnight; from midnight to midnight, it lasts all day. The change is sent to the mower when you confirm.", "La tondeuse tond pendant ces créneaux, aux jours sélectionnés. Un créneau peut finir à minuit ; de minuit à minuit, il dure toute la journée. La modification est envoyée à la tondeuse quand vous confirmez."),
    "ScheduleEditor_Start.Header": ("Start", "Début"),
    "ScheduleEditor_End.Header": ("End", "Fin"),
    "ScheduleEditor_Add.Content": ("Add a time slot", "Ajouter un créneau"),
    "ScheduleEditor_Empty.Text": ("No time slot: the mower will not start on its own.", "Aucun créneau : la tondeuse ne démarrera pas toute seule."),
    f"ScheduleEditor_Remove.{TT}": ("Remove this slot", "Supprimer ce créneau"),
    f"ScheduleEditor_Remove.{AN}": ("Remove this slot", "Supprimer ce créneau"),
    "Issue_NoDays": ("Slot {0}: select at least one day.", "Créneau {0} : sélectionnez au moins un jour."),
    "Issue_EndBeforeStart": ("Slot {0}: the end must be after the start.", "Créneau {0} : la fin doit être après le début."),
    "Issue_CrossesMidnight": ("Slot {0} cannot continue past midnight.", "Le créneau {0} ne peut pas dépasser minuit."),
    "Issue_Overlap": ("Slots {0} and {1} overlap on {2}.", "Les créneaux {0} et {1} se chevauchent le {2}."),
    "Command_ScheduleSent": ("Schedule sent to the mower.", "Planning envoyé à la tondeuse."),
    "Detail_StatisticsHeader.Text": ("Statistics", "Statistiques"),
    "Detail_ResetBlades.Content": ("Reset blade counter", "Remettre à zéro le compteur des lames"),
    "Detail_PositionHeader.Text": ("Last known position", "Dernière position connue"),
    "Detail_OpenMap.Content": ("Open in OpenStreetMap", "Ouvrir dans OpenStreetMap"),
    "Detail_Recenter.Content": ("Recenter", "Recentrer"),
    "Detail_TrackHint.Text": ("Line: the last positions reported by the mower (the large dot is the most recent one, the small one the oldest).", "Trait : les dernières positions signalées par la tondeuse (le grand point est la plus récente, le petit la plus ancienne)."),
    "Nav_Map.Content": ("Map", "Carte"),
    "Nav_Quit.Content": ("Quit", "Quitter"),
    f"Nav_Quit.{TT}": ("Quit HusqA Cockpit", "Quitter HusqA Cockpit"),
    "Map_Title.Text": ("Map", "Carte"),
    "Map_RecenterText.Text": ("Recenter", "Recentrer"),
    f"Map_Recenter.{TT}": ("Zoom back on the tracks of all mowers", "Recadrer la carte sur les tracés de toutes les tondeuses"),
    "Map_Empty.Text": ("No GPS position available yet.", "Aucune position GPS disponible pour l'instant."),
    "Map_Unavailable": ("The map needs the Microsoft Edge WebView2 runtime, which could not be started.", "La carte nécessite le runtime Microsoft Edge WebView2, qui n'a pas pu démarrer."),
    "Map_GetWebView2.Content": ("Download WebView2", "Télécharger WebView2"),
    "Detail_MessagesHeader.Text": ("Event history", "Historique des événements"),
    "Detail_LoadMessages.Content": ("Load history", "Charger l'historique"),
    "Detail_NoMessages.Text": ("No events recorded.", "Aucun événement enregistré."),

    "Settings_Title.Text": ("Settings", "Paramètres"),
    "Settings_ApiHeader.Text": ("Husqvarna API", "API Husqvarna"),
    "Settings_ApiHelp.Text": ("Create an application on the Husqvarna developer portal, connect it to the “Authentication API” and “Automower Connect API”, then copy its key and secret here.",
                              "Créez une application sur le portail développeur Husqvarna, connectez-la aux API « Authentication API » et « Automower Connect API », puis copiez ici sa clé et son secret."),
    "Settings_ApiPortal.Content": ("Open the Husqvarna developer portal", "Ouvrir le portail développeur Husqvarna"),
    "Settings_ApplicationKey.Header": ("Application key", "Clé d'application (Application key)"),
    "Settings_ApplicationKey.PlaceholderText": ("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"),
    "Settings_ApplicationSecret.Header": ("Application secret", "Secret d'application (Application secret)"),
    "Settings_Save.Content": ("Save and connect", "Enregistrer et se connecter"),
    "Settings_Test.Content": ("Test", "Tester"),
    "Settings_Delete.Content": ("Delete", "Supprimer"),
    "Settings_ApiStorage.Text": ("The key and secret are stored in the Windows Credential Manager of your user account, never in plain text.", "La clé et le secret sont stockés dans le Gestionnaire d'identification Windows de votre compte, jamais en clair."),
    "Settings_NotificationsHeader.Text": ("Notifications", "Notifications"),
    "Settings_NotifyErrors.Header": ("When a mower reports an error or an alarm", "Quand une tondeuse signale une erreur ou une alarme"),
    "Settings_NotifyRecoveries.Header": ("When a mower recovers from an error", "Quand une tondeuse se remet d'une erreur"),
    "Settings_NotifyStopped.Header": ("When a mower stops and needs a manual action", "Quand une tondeuse s'arrête et demande une intervention"),
    "Settings_NotifyConnectivity.Header": ("When a mower loses or regains its connection", "Quand une tondeuse perd ou retrouve sa connexion"),
    "Settings_TaskNotifications.Header": ("Notifications when a mower starts or finishes mowing", "Notifications de début et de fin de tonte"),
    "Settings_TestNotification.Content": ("Send a test notification", "Envoyer une notification de test"),
    "Settings_BehaviorHeader.Text": ("Behavior", "Comportement"),
    "Settings_CloseToTray.Header": ("Keep running in the notification area when the window is closed", "Rester actif dans la zone de notification quand la fenêtre est fermée"),
    "Settings_StartWithWindows.Header": ("Start with Windows (in the notification area)", "Démarrer avec Windows (dans la zone de notification)"),
    "Settings_PollingInterval.Header": ("Refresh interval without real-time updates", "Intervalle d'actualisation sans temps réel"),
    "Settings_PollingHelp": ("Husqvarna allows {0} requests per month per key. Every {1} minutes uses about {2} requests per month.", "Husqvarna autorise {0} requêtes par mois et par clé. Toutes les {1} minutes représente environ {2} requêtes par mois."),
    "Settings_LanguageHeader.Text": ("Language", "Langue"),
    "Settings_Language.Header": ("Display language", "Langue d'affichage"),
    "Settings_LanguageSystem.Content": ("Automatic (Windows language)", "Automatique (langue de Windows)"),
    "Settings_RestartRequired.Title": ("Restart required", "Redémarrage nécessaire"),
    "Settings_RestartRequired.Message": ("HusqA Cockpit must restart to apply the new language.", "HusqA Cockpit doit redémarrer pour appliquer la nouvelle langue."),
    "Settings_RestartNow.Content": ("Restart now", "Redémarrer maintenant"),
    "Settings_AboutHeader.Text": ("About", "À propos"),
    "Settings_Disclaimer.Text": ("Unofficial application, not affiliated with Husqvarna. Automower® is a trademark of Husqvarna AB.", "Application non officielle, sans lien avec Husqvarna. Automower® est une marque de Husqvarna AB."),
    "Settings_SourceCode.Content": ("Source code", "Code source"),
    "Settings_OpenLogs.Content": ("Open the logs folder", "Ouvrir le dossier des journaux"),
}
